name: Crawl dataset
on: 
  schedule:
    - cron: '0 5 * * *'
  push:
    branches:
      - 'f/crawl'

jobs:
  crawl-data:
    runs-on: ubuntu-18.04
    env:
      MONGODB_USER: ${{ secrets.MONGODB_USER }}
      MONGODB_PASSWORD: ${{ secrets.MONGODB_PASSWORD }}
      DATASOURCE_TEST: ${{ secrets.DATASOURCE_TEST }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.6'
          cache: 'pip'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Crawl data
        run: |
          export PYTHONPATH=.
          python3 crawling/threader.py
